# Generated by Django 5.1.4 on 2024-12-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
